language: cpp

compiler:
  - clang
  - gcc

os: linux
dist: jammy

addons:
  apt:
    packages:
      libboost-dev
      libnetcdf-c++4-dev
      libnetcdf-dev
      cmake

#jobs:
#  include:
#    os: osx
#    osx_image: xcode12.3
#    compiler: clang
#    addons:
#      homebrew:
#        packages:
#          - boost
#          - sundials

script:
  - git clone https://github.com/toruniina/toml11
  - cp Makefile.local.travisci Makefile.local
  - ./build_sundials
  - make
  - make test
  - make unit_tests
