language: cpp

compiler:
  - clang
  - gcc

os: linux
dist: bionic

addons:
  apt:
    packages:
      libboost-dev
      cmake

jobs:
  include:
    os: osx
    osx_image: xcode12.3
    compiler: clang
    addons:
      homebrew:
        packages:
          - boost
          - sundials

script:
  - git clone https://github.com/toruniina/toml11
  - cp Makefile.local.travisci Makefile.local
  - make
  - make test
