version: 2.1

executors:
  debian-bullseye:
    docker:
      - image: buildpack-deps:bullseye
  ubuntu-focal:
    docker:
      - image: buildpack-deps:focal



jobs:
  builddebian:
    docker:
      - image: buildpack-deps:bullseye
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install --quiet --yes g++-10 libboost-dev cmake libnetcdf-dev libnetcdf-c++4-dev
      - run:
          command: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run:
          command: ./build_sundials
      - run:
          command: cp Makefile.local.example Makefile.local
      - run:
          command: CXX="g++-10" make
      - run:
          command: make test
  buildubuntu:
    docker:
      - image: buildpack-deps:focal
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install --quiet --yes g++-10 libboost-dev cmake libnetcdf-dev libnetcdf-c++4-dev
      - run:
          command: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run:
          command: ./build_sundials
      - run:
          command: cp Makefile.local.example Makefile.local
      - run:
          command: CXX="g++-10" make
      - run:
          command: make test
workflows:
  main:
    jobs:
      - builddebian
      - buildubuntu
