version: 2.1

jobs:
  builddebian:
    docker:
      - image: buildpack-deps:bullseye
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install --quiet --yes g++-10 libboost-dev cmake libnetcdf-dev libnetcdf-c++4-dev python3-netcdf4
      - run:
          command: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run:
          command: ./build_sundials
      - run:
          command: cp Makefile.local.example Makefile.local
      - run:
          command: CXX="g++-10" make
      - run:
          command: make test
      - run:
          command: make unit_tests
  buildubuntu:
    docker:
      - image: buildpack-deps:jammy
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install --quiet --yes g++-10 libboost-dev cmake libnetcdf-dev libnetcdf-c++4-dev python3-netcdf4
      - run:
          command: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run:
          command: ./build_sundials
      - run:
          command: cp Makefile.local.example Makefile.local
      - run:
          command: CXX="g++-10" make
      - run:
          command: make test
      - run:
          command: make unit_tests
  buildmacos:
    macos:
      xcode: 13.4.1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew install coreutils boost sundials netcdf cmake
      - run: BUILD_NETCDFCXX=Y HDF5_DIR="/usr/local/opt/hdf5" NETCDF_DIR="/usr/local/opt/netcdf" ./build_netcdf_cxx
      - run: HDF5_DIR="/usr/local/opt/hdf5" pip3 install netcdf4
      - run: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run: cp Makefile.local.circleci_osx Makefile.local
      - run: make
      - run: make test
      - run: make unit_tests


workflows:
  main:
    jobs:
      - builddebian
      - buildubuntu
      - buildmacos
