version: 2.1

jobs:
  builddebian:
    docker:
      - image: buildpack-deps:bullseye
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install --quiet --yes g++-10 libboost-dev cmake libnetcdf-dev libnetcdf-c++4-dev
      - run:
          command: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run:
          command: ./build_sundials
      - run:
          command: cp Makefile.local.example Makefile.local
      - run:
          command: CXX="g++-10" make
      - run:
          command: make test
      - run:
          command: make unit_tests
  buildubuntu:
    docker:
      - image: buildpack-deps:jammy
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install --quiet --yes g++-10 libboost-dev cmake libnetcdf-dev libnetcdf-c++4-dev
      - run:
          command: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run:
          command: ./build_sundials
      - run:
          command: cp Makefile.local.example Makefile.local
      - run:
          command: CXX="g++-10" make
      - run:
          command: make test
      - run:
          command: make unit_tests
  buildmacos:
    macos:
      xcode: 13.4.1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew install boost sundials wget
      - run: curl -L https://github.com/macports/macports-base/releases/download/v2.7.2/MacPorts-2.7.2-12-Monterey.pkg --output macports.pkg; sudo installer -package macports.pkg -target /
      - run: ports install netcdf netcdf-cxx4
      - run:
          command: git clone https://github.com/ToruNiina/toml11.git toml11/
      - run:
          command: cp Makefile.local.osx Makefile.local
      - run:
          command: make
      - run:
          command: make test
      - run:
          command: make unit_tests


workflows:
  main:
    jobs:
      - builddebian
      - buildubuntu
      - buildmacos
